### ISSUE TITLE
Google Home Resume script not working with Music Assistant!?

### ISSUE THREAD

**Issue by marschallphilipp** [TheFes/HA-configuration#48]
Hi there,
I managed to resume media which I started via Spotcast (triggered through the "custom:spotify-card") but media is not resumed when playing media with the newly integrated Music Assitant.
Do you think your script can be changed in order to work with this integration?

Furthermore I noticed that on my Google minis the volume level is changed before the originally played media is completely stopped, e.g. when altering the volume level for tts messages the originally played media gets pretty loud for a short time before tts is played.

**Comment by TheFes** [comment]
Hi,

I've had a look at Music Assistant, it seems it uses local media. I'm not using it myself, but I would expect it would work already, at least to resume the current song. But I will install it myself and look if I can get it working completely.

For the volume, I can try if I can prevent that. The problem is that with multiple targets it could be that they are never all idle at the same time, so it could be that there is never a moment to apply the right volume. I could give it a go with the helper script.

I'll come back to you with a test version as soon as I have something to test :)

**Comment by TheFes** [comment]
Oh wait, looking better to Music Assistant now. Do you have this issue when you are playing Spotify through Music Assistant?

**Comment by TheFes** [comment]
After gathering some more information, I think I can support Music Assistant in my script as well. I'll let you know when I have something to test

**Comment by TheFes** [comment]
If you want you can test this version, which should work with Music Assistant
https://github.com/TheFes/HA-configuration/blob/TheFes/issue48/include/script/00_general/google_cast/google_home_resume.yaml

With regards to the volume, I remember now what the problem was. In the past I added a wait template which waited until the player was idle, and then changed the volume. However, in my own setup I noticed that sometimes the player immediately switched from playing music, to playing the TTS, there was no pause between. So then the volume change would be applied after the TTS. As this was not wanted, I removed the wait template, so indeed it could be that the volume change is applied to soon.
I will give this another thought.
