### ISSUE TITLE
Google Home Resume - Helper script. Error: Could not find device with name xxxxxxx

### ISSUE THREAD

**Issue by blanquis80** [TheFes/HA-configuration#74]
Recently installed this new package, however when testing I can never get it to resume (spotfify). Looking at the two trace files, it looks like the Google Home Resume script finishes, but the helper script errors out complaining about not being able to find my cast device

"Could not find device with name Office Display"

Both trace JSON files have been attached. had to rename the extention to .txt

[trace script.google_home_resume_helper 2023-01-05T04_03_30.788692+00_00.json.txt](https://github.com/TheFes/HA-configuration/files/10349416/trace.script.google_home_resume_helper.2023-01-05T04_03_30.788692%2B00_00.json.txt)
[trace script.google_home_resume 2023-01-05T04_03_25.016678+00_00.json.txt](https://github.com/TheFes/HA-configuration/files/10349418/trace.script.google_home_resume.2023-01-05T04_03_25.016678%2B00_00.json.txt)

**Comment by TheFes** [comment]
Unfortunately this is an error caused by Spotcast, which I can not resolve.
For me this helped:
https://github.com/fondberg/spotcast/issues/365#issuecomment-1356797204

The adjusted files are also on my repo: https://github.com/TheFes/HA-configuration/tree/main/custom_components/spotcast

You can give that a try, if it doesn't work please create an issue on the spotcast repo, or try the topic on the HA community forum.

**Comment by blanquis80** [comment]
Thanks. Much appreciated.
